name: Swift CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: swift-actions/setup-swift@v1
    - uses: actions/checkout@v3
    - name: Swift Version
      run: swift --version
    - name: Build
      run: swift build -c release --static-swift-stdlib
    - name: Run tests
      run: swift test -v
